
#This will create this metric in all the tiers, under this path
metricPrefix: Custom Metrics|MqttBrokers

#This will create it in specific Tier. Replace <TIER_NAME>
#metricPrefix: Server|Component:<TIER_NAME>|Custom Metrics|Memcached

# List of Memcached Servers
servers:
  #"MQTT broker URI to connect to. tcp://127.0.0.1:port(1883) or mqtt://127.0.0.1:port(1883).
  #Use ws:// for Websockets, wss:// for secure Websockets and ssl:// for TLS encrypted TCP connections."
  - host: "mqtt://127.0.0.1:1883"
    displayName: "localhost_test1" #will be used in metric browser so make sure unique
    clientID: "localtest_1" #unique id for client, if empty uses displayName and timestamp
    keepAlive: 60 #keep alive in seconds, if nothing set 60 is default
    username: #if broker requires set here
    password: #if broker requires set here
    qos: 0 #we don't want retention etc so valid values are 0, 1, 2
    topics: # a list of topics, we make configurable here, but it's likely following closely to the relevant sys topics outlined: https://github.com/mqtt/mqtt.org/wiki/SYS-Topics
      - metric_name: "subscription_count"
        metric_topic: "$SYS/broker/subscriptions/count"
      - metric_name: "messages_stored"
        metric_topic: "$SYS/broker/messages/stored"
      - metric_name: "connection_load_1min"
        metric_topic: "$SYS/broker/load/connections/1min"
      - metric_name: "socket_load_1min"
        metric_topic: "$SYS/broker/load/sockets/1min"
    will-retain: false #TODO this is only for publishing so probably remove
    will-payload: "I died" #TODO this is to notify other subscribers our client disconnected, probably remove for this purpose
    will-topic: "localtest_1/status" #TODO this is to notify other subscribers our client disconnected, probably remove for this purpose
    clean-session: true #client connects with clean session, we don't expect to pickup stored messages
    max-inflight: 10 #TODO default is 10, but this is for publishing so probably remove
    automatic-reconnect: true #auto reconnect on which is likely what we always want for this



#timeout in ms to get data for all the servers
timeout: 60000
numberOfThreads: 5


controllerInfo:
  controllerHost: ""
  controllerPort: 8090
  account: ""
  username: ""
  password: ""
  encryptedPassword: ""
  controllerSslEnabled: false
  enableOrchestration: false
  uniqueHostId: ""
  accountAccessKey: ""
  machinePath: ""
  simEnabled: true
  applicationName: ""
  tierName: ""
  nodeName: ""